# Generated by Django 3.1.4 on 2021-05-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0002_auto_20210520_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(db_column='university', null=True, on_delete=django.db.models.deletion.CASCADE, to='stelaapp.university'),
        ),
    ]
